app/models.py
class Articles:


 def __init__(self,author,title,description,url,urlToImage,publishedAt):
        self.author= author
        self.title = title
        self.description = description
        self.url= url
        self.urlToImage= urlToImage
        self.publishedAt = publishedAt
       
        

class News:
    '''
    News class to define News Objects
    '''

    def __init__(self,id,name,description,url,category,language,country):
        self.id =id
        self.name = name
        self.description= description
        self.url = url
        self.category= category
        self.language = language
        self.country = country
        

app/models/news.py
class News:
    '''
    News class to define News Objects
    '''

    def __init__(self,id,name,description,url,category,language,country):
        self.id =id
        self.name = name
        self.description= description
        self.url = url
        self.category= category
        self.language = language
        self.country = country
        

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap

bootstrap = Bootstrap()

def create_app(config_name):
    
    # Initializing application
    app = Flask(__name__,instance_relative_config = True)

    # Setting up configuration
    app.config.from_object(config_options[config_name])
    
    #initialising blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # Initializing Flask Extensions
    bootstrap.init_app
    
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import render_template
from . import main
from app.request import get_sources
from app.request1 import get_news_home

# Views
@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''
    
    popular_news = get_news_home()
    name = 'Home - Welcome to Trending news'
    return render_template('index.html', name=name,popular_news = popular_news)
  
@main.route('/news')
def news():

    '''
    View news page function that returns the news details page and its data
    '''
    sources = get_sources()
    return render_template('articles.html', sources=sources)

app/templates/articles.html
{% extends 'base.html'%}

{% block content %}

<div>

    <div class="container">
  <br>
   <div class="jumbotron image-responsive" style="background-image: url(https://thewallpaper.co//wp-content/uploads/2016/03/earth-at-night-from-space-hd-wallpaper-iphone-background-images-abstract-colorful-1920x1080.jpg);">
  <h3 style="text-align:center; color:wheat" class="display-3">THE NEWS {{ name_source }}</h3><br><br><br><br><br>><br>><br>
   </div>
 
    <div class="card-columns">
      {% for source in sources %}

      <div class="card border-secondary">
        <div class="card-body bg-warning">
          <div class="card-title"><a href="{{source.url}}" class="card-link">{{source.name}}</a></div>
          <div class="card-text">
            {{source.description}}
          </div>
          </div>
      </div>
      {% endfor %}

    </div>
  </div>

  {% endblock%}
</body>>

app/templates/base.html
<!-- Navbar block  --> 


<!DOCTYPE html>
<html>
    <head>
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
            <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.6/css/mdb.min.css" rel="stylesheet">
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
    
        {% endif %}
    </head>
    <body>
        {% block navbar %}
        {% include 'navbar.html' %}
        {% endblock %}
        <!-- Content block -->

        {% block content %}

        {% endblock%}
    </body>
</html>

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

<!-- Styles block -->

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
<!-- Content block -->
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  {% if title %}
  <title> {{ title }}</title>
  {% else %}
  <title> Welcome to our News headlines </title>
  {% endif %}
</head>

<body>
  <!-- Content block -->
  {% block content %}
  <div class="container-fluid">
    <div class="row">
  {% for highlight in popular_news %}


    <div class=" col-sm-4">
      <div class="card bg-warning">
        <img src="{{highlight.urlToImage}}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{highlight.title}}</h5>
          <p class="card-text">{{highlight.description}}</p>
          <p class="card-text">{{highlight.country}}</p>
          <p class="card-text">
            <br>
             {{highlight.author}}
          </p>
          <p><a href="{{highlight.url}}" class="card-link">Read Full Story</a></p>
          <p>{{highlight.publishedAt}}</p>
        </div>
      </div>
    </div>


  {% endfor %}
  </div>
  </div>

  {% endblock%}
</body>

</html>

app/templates/macros.html
{% macro displayArticlesList(articles_list) %}

    {% for articles in articles_list %}
        <div class="col-xs-12 col-sm-4 col-md-2 col-lg-2 movie-card">
            <img src="{{ articles.urlToImage }}" alt="{{ articles.title }} url" class="img-responsive">
            <li class="text-center">
                <a href="/articles/{{articles.id}}">
                    {{ articles.title|truncate(10)}}</a>
            </li>
        </div>

    {% endfor %}

{% endmacro %}

{% macro displayArticlesList(popular_list)%}
    {% for source in popular_news %}
    <div class="card border-secondary">
            <div class="card-body  bg-warning">
            <img src="{{source.urlToImage}}" class="card-img-top" alt="...">
              <div class="card-title">{{source.title}}</div>
              <div class="card-text">
                {{source.description}}
               </div>
              <a href="{{source.url}}" class="card-link">Read Full Story</a>
    
            </div>
    
            <footer class="blockquote-footer"> <cite title="Source Title">Posted on {{source.publishedAt}} </cite></footer>
          </div>

    {% endfor %}

{% endmacro %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">NEWS HIGHLIGHTS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{{url_for('main.news')}}">Home</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{{url_for('main.index')}}">highlights</a>
            </li>
            
          </ul>
        </div>
      </nav>